"""initial migration

Revision ID: 1396b18fb607
Revises: d8db7b684922
Create Date: 2023-12-24 22:33:38.286439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1396b18fb607'
down_revision = 'd8db7b684922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
